### ISSUE TITLE
Hi, are you still working on dliom?

### ISSUE THREAD

**Issue by JaySlamer** [juliangaal/slam_collection#1]
I found out you deleted your dliom repo long ago. Did you give up or chose to work on it privately?

**Comment by juliangaal** [comment]
was forced to set to private. Company policy, sry.

Have you found other implementations?

**Comment by JaySlamer** [comment]
> Have you found other implementations?



> was forced to set to private. Company policy, sry.
> 
> Have you found other implementations?

Thank you for asking
I have added a lio-sam-like posegraph optimization to it, then implemented pure localization on built map , and multiple lidars. After implementing all these functionalities I seperated front end and back end into different threads using std::async. I also removed all the similarity related computations because they are too heavy for my industrial PC. These are what I have done so far.

**Comment by juliangaal** [comment]
that was roughly my state as well. I did have an issue with correcting the local map after pgo. Does that work for you?

I had a similar experience with jaccardian similarity calculation. The calculations were in itself fast enough with an Octree, but you would have to update the similarities every time the graph changes. 
a) is this even worth it? 
b) adds even more complexity because this would also have to be handled in a separate thread

**Comment by JaySlamer** [comment]
> that was roughly my state as well. I did have an issue with correcting the local map after pgo. Does that work for you?
> 
> I had a similar experience with jaccardian similarity calculation. The calculations were in itself fast enough with an Octree, but you would have to update the similarities every time the graph changes. a) is this even worth it? b) adds even more complexity because this would also have to be handled in a separate thread

About the local map:
I calculate and save clouds deskewed but not transformed,aka deskewed clouds in lidar frame. Every time when a local map is needed I use the current pose estimations of keyframes to transform these clouds and assemble them into a local map.  Maybe because I started from one thread, so I did not encounter a problem correcting front end using back end, but it did take me quite some time to figure out how to separate them.
Glad to know that you have overcome this problem.

**Comment by juliangaal** [comment]
Sry for not getting back to you, DLIOM is not really on my radar anymore due to other work.

In any case, this may be of interest for you, shameless plug: [nanoflann_pcl](https://github.com/juliangaal/nanoflann_pcl)

**Comment by juliangaal** [comment]
Any way I can contact you outside of github?

**Comment by JaySlamer** [comment]
> Any way I can contact you outside of github?

My email : 54495012@qq.com
My phone: +8615396664418
If you happen to use Telegram app, you can contact me on it.
